#%RAML 0.8
---
title: Hack 24
baseUri: https://api.hack24.co.uk
version: 2016-02-19
/teams:
  displayName: Teams Resource
  description: |
    Allows creating and modifying teams and team members
  get:
    responses:
      200:
        body:
          application/vnd.api+json:
            example: !include examples/responses/teams-get.json
  post:
    body:
      application/vnd.api+json:
        example: !include examples/requests/teams-post.json
    responses:
      201:
        body:
          application/vnd.api+json:
            example: !include examples/responses/teams-post.json
        
  /{teamId}:
    displayName: Team Resource
    description: |
      Returns a specific team.
    uriParameters:
      teamId:
        displayName: Team ID
        type: string
    get:
      responses:
        200:
          body:
            application/vnd.api+json:
              example: !include examples/responses/team-get.json

    /members:
      displayName: Team Members Relationship
      description: |
        Manages team members for the current team.
      get:
        responses:
          200:
            body:
              application/vnd.api+json:
                example: !include examples/responses/team-members-get.json
      post:
        body:
          application/vnd.api+json:
            example: !include examples/requests/team-members-post.json
        responses:
          200:
            body:
              application/vnd.api+json:
                example: !include examples/responses/team-members-post.json
      patch:
        body:
          application/vnd.api+json:
            example: !include examples/requests/team-members-patch.json
        responses:
          200:
            body:
              application/vnd.api+json:
                example: !include examples/responses/team-members-patch.json
      delete:
        body:
          application/vnd.api+json:
            example: !include examples/requests/team-members-delete.json
        responses:
          204:

/users:
  displayName: Users Resource
  description: |
    Allows creating and modifying users
  get:
    responses:
      200:
        body:
          application/vnd.api+json:
            example: !include examples/responses/users-get.json
  post:
    body:
      application/vnd.api+json:
        example: !include examples/requests/users-post.json
    responses:
      201:
        body:
          application/vnd.api+json:
            example: !include examples/responses/users-post.json

  /{userId}:
    displayName: User Resource
    description: |
      Returns a specific user.
    get:
      responses:
        200:
          body:
            application/vnd.api+json:
              example: !include examples/responses/user-get.json

    /team:
      displayName: User Team Relationship
      description: |
        Manages a user's team.
      get:
        responses:
          200:
            body:
              application/vnd.api+json:
                example: !include examples/responses/user-team-get.json
      patch:
        body:
          application/vnd.api+json:
            example: !include examples/requests/user-team-patch.json
        responses:
          204:
